### ISSUE TITLE
Sometimes two tabs are created instead of one

### ISSUE THREAD

**Issue by emmatyping** [IronManMark20/Explore10#1]

**Comment by emmatyping** [comment]
I think this is fixed.

**Comment by Krutonium** [comment]
Can confirm, haven't seen.

**Comment by emmatyping** [comment]
Awesome, if it does come back, please let me know

**Comment by Krutonium** [comment]
Will do.

**Comment by Krutonium** [comment]
Okay, so it's happening now. No idea how to reproduce.

**Comment by emmatyping** [comment]
Yeah, it is persnickety

**Comment by emmatyping** [comment]
Again, should be closed due to latest commit, if this continues, please leave a comment or reopen
