### ISSUE TITLE
File -> Open Command Prompt

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/Explore10#12]
Change your opening execution from just running cmd.exe to

```
cmd.exe /K cd "PathTheUserIsIn"
```

**Comment by emmatyping** [comment]
Ah. I  had tried that. My syntax must've  been wrong.

**Comment by Krutonium** [comment]
In vb I would do this:

Dim P as ProcessStartInfo
P.filename = "cmd.exe"
P.arguments = "/K cd ""path"""
Process.start(P)

**Comment by emmatyping** [comment]
Same in C#. I  read about it,  but didn't implement

**Comment by Krutonium** [comment]
I am working on this in my branch, but how do I get the CD?
