### ISSUE TITLE
Closing Tabs in a certain order can crash

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/Explore10#14]
var item = tabDynamic.Items.Cast<TabItem>().Where(i => i.Name.Equals(tabName)).SingleOrDefault();

In MainWindow.xaml.cs

Open a tab, switch to it, close the first, open a new tab, switch to it, close the first, crash.

**Comment by Krutonium** [comment]
Update: Seems that repeatedly closing any tab will cause this.

**Comment by emmatyping** [comment]
I would be concerned if you could repeatedly close a tab

**Comment by Krutonium** [comment]
I mean if you open a bunch and close the one in a certain spot multiple times.

**Comment by emmatyping** [comment]
This should be fixed with the new and improved tab logic. Re-open if it still exists.
