### ISSUE TITLE
When opening the application, this is in the log

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/Explore10#23]
System.Windows.Data Warning: 5 : Value produced by BindingExpression is not valid for target property.; Value='NaN' BindingExpression:Path=Height; DataItem='Grid' (Name='ParentGrid'); target element is 'ScrollViewer' (Name=''); target property is 'MinHeight' (type 'Double')

**Comment by emmatyping** [comment]
Noted. I need to eliminate this. Not entirely sure what is causing this

**Comment by emmatyping** [comment]
I'll close this in the next PR

**Comment by emmatyping** [comment]
Looks good (I hope). Closing
