### ISSUE TITLE
Right Clicking anything causes a crash 

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/Explore10#38]
ShellContextMenu.cs Line 249 : NullReferanceException

**Comment by emmatyping** [comment]
This is part of Gong-Shell, so I will update the sub repo.

Hmmm. Wait. Need to update the gong-shell submodule.

**Comment by emmatyping** [comment]
As a brief fix until I update the submodule, you can delete that line.

**Comment by emmatyping** [comment]
Fixed in last commit
