### ISSUE TITLE
License for project

### ISSUE THREAD

**Issue by emmatyping** [IronManMark20/Explore10#7]
I need to decide on this

**Comment by emmatyping** [comment]
Well, GPL is out of the question.
I'm thinking BSD 3- clause

**Comment by Krutonium** [comment]
What about GPLv3?

**Comment by emmatyping** [comment]
Not compatible with distributing MahApps.Metro source

**Comment by Krutonium** [comment]
Lemme make a PR...

**Comment by emmatyping** [comment]
About what?
NM
