### ISSUE TITLE
Not sure how, but I got the file manager stuck in a folder, unless I manually navigated away

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/Explore10#8]
Couldn't go back, nor could I go up.

**Comment by emmatyping** [comment]
Probably a bug in the navigation logic

**Comment by Krutonium** [comment]
Seems to happen when you spam the Up button.

And I can't navigate away this time.

**Comment by Krutonium** [comment]
Seems to happen reliably if you go 3 folders deep and try to return to C: using the up button,

**Comment by emmatyping** [comment]
I will check this out when am front of computer again

**Comment by emmatyping** [comment]
The up button has been changed with better logic a few commits ago, so I'm closing this.
