### ISSUE TITLE
Hamburger -> This PC

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/Explore10#9]
An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll

Additional information: The device is not ready.

StartPage.xaml.cs

**Comment by emmatyping** [comment]
That is unexpected. Do you mean This PC?

**Comment by Krutonium** [comment]
Yes,

It dies on the line Label.Text = di.VolumeLabel;

**Comment by emmatyping** [comment]
`(1) the drive is empty; (2) the drive door is open; or (3) the drive is in use.` hmmm

EDIT: `ERROR_NOT_READY normally indicates a serious hardware failure.` https://social.msdn.microsoft.com/Forums/en-US/0af621aa-db84-4fde-9c9e-5545b8b65601/the-device-is-not-ready-error-message?forum=Vsexpressvcs
